### ISSUE TITLE
Add support for project references

### ISSUE THREAD

**Issue by nickrandolph** [davidwengier/AllGlobalUsingsGenerator#1]
I get that this was just a hack project, but how hard would it be to add namespaces from project references, in addition to package (ie assembly) references?

**Comment by davidwengier** [comment]
Yep, should be easy enough. [This line](https://github.com/davidwengier/AllGlobalUsingsGenerator/blob/main/AllGlobalUsingsGenerator/Generator.cs#L43) will be the thing stopping them working, but it was only intended to stop namespaces from the target project being added.

**Comment by davidwengier** [comment]
Fixed.  I'm sure its small comfort, but this would have been working fine in production, just not in VS 😛
